server:
  port: 8080
  servlet:
    context-path: /

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserDb
      auto-index-creation: true
  test:
    database:
      replace: none

# JWT Configuration (DO NOT ADD SECRETS HERE)
# These values should be set via environment variables:
# - SECURITY_JWT_SECRET_KEY
# - SECURITY_JWT_REFRESH_SECRET_KEY
jwt:
  expiration-ms: 86400000
  refresh-expiration-ms: 604800000

security:
  jwt:
    expiration-ms: 2400000
    refresh-expiration-ms: 86400000
  auth:
    # secret-key: # Value removed, Use environment variable SECURITY_JWT_SECRET_KEY
    # refresh-secret-key: # Value removed, Use environment variable SECURITY_JWT_REFRESH_SECRET_KEY
    secret-key: ${SECURITY_JWT_SECRET_KEY:VGhpc0lzQTMyQ2hhcmFjdGVyTG9uZ1NlY3JldEtleUZvckpXVDEyMzQ1} # Use env var, fallback only for local dev if needed
    refresh-secret-key: ${SECURITY_JWT_REFRESH_SECRET_KEY:VGhpc0lzQTMyQ2hhcmFjdGVyTG9uZ1JlZnJlc2hLZXlGb3JKV1QxMjM0NQ==} # Use env var, fallback only for local dev if needed
  basic:
    enabled: false
  cors:
    allowed-origins: http://localhost:3000,http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: Authorization,Content-Type,Accept,Origin,X-Requested-With
    exposed-headers: Authorization,Content-Disposition
    allow-credentials: true
    max-age: 3600
  headers:
    enable-hsts: true
    hsts-max-age: 31536000
    hsts-include-sub-domains: true
    content-security-policy: default-src 'self'; frame-ancestors 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';
    referrer-policy: strict-origin
    enable-xss-protection: true
    deny-frame-options: true
  account:
    lockout:
      max-attempts: 5
      duration: 300000
  lockout:
    initial-delay: PT1S
    max-delay: PT5S

token:
  storage:
    strategy: MEMORY

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    filter: true
    disable-swagger-default-url: true
    enabled: true
  packages-to-scan: genaidemopoc.ecommerceproj.jwtspringsecurity.usersvc

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG
    genaidemopoc.ecommerceproj.jwtspringsecurity: DEBUG
    genaidemopoc.ecommerceproj.jwtspringsecurity.usersvc.security: TRACE
    genaidemopoc.ecommerceproj.jwtspringsecurity.usersvc.service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/v1/application.log
    max-size: 10MB
    max-history: 5

management:
  security:
    enabled: false
